/** Additive integration storage fragment. Composition into control migrations is owned by the root. */
export const INTEGRATION_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS integration_packs (id TEXT PRIMARY KEY, label TEXT, subject_refs_json TEXT NOT NULL CHECK(json_valid(subject_refs_json)), requirements_json TEXT NOT NULL CHECK(json_valid(requirements_json)), created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS integration_pack_revisions (pack_id TEXT NOT NULL, revision INTEGER NOT NULL, content_digest TEXT NOT NULL, manifest_json TEXT NOT NULL CHECK(json_valid(manifest_json)), snapshot_path TEXT NOT NULL, registered_at INTEGER NOT NULL, PRIMARY KEY(pack_id, revision), UNIQUE(pack_id, content_digest), FOREIGN KEY(pack_id) REFERENCES integration_packs(id));
CREATE TABLE IF NOT EXISTS integration_capability_implementations (pack_id TEXT NOT NULL, pack_revision INTEGER NOT NULL, capability TEXT NOT NULL, contract_revision INTEGER NOT NULL, mode TEXT NOT NULL CHECK(mode IN ('script','declarative')), support_status TEXT NOT NULL CHECK(support_status IN ('implemented','unsupported')), support_reason TEXT, implementation_json TEXT NOT NULL CHECK(json_valid(implementation_json)), check_status TEXT NOT NULL CHECK(check_status IN ('unchecked','compatible','incompatible','degraded')), semantics_verified INTEGER NOT NULL DEFAULT 0 CHECK(semantics_verified IN (0,1)), checked_at INTEGER, diagnostics_json TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(diagnostics_json)), PRIMARY KEY(pack_id, pack_revision, capability), FOREIGN KEY(pack_id, pack_revision) REFERENCES integration_pack_revisions(pack_id, revision));
CREATE TABLE IF NOT EXISTS integration_checks (id TEXT PRIMARY KEY, pack_id TEXT NOT NULL, pack_revision INTEGER NOT NULL, implementation_id TEXT NOT NULL, capability TEXT NOT NULL, contract_id TEXT NOT NULL, contract_revision INTEGER NOT NULL, target_json TEXT NOT NULL CHECK(json_valid(target_json)), checked_at INTEGER NOT NULL, result TEXT NOT NULL CHECK(result IN ('compatible','incompatible','degraded')), semantics_verified INTEGER NOT NULL CHECK(semantics_verified IN (0,1)), evidence_json TEXT NOT NULL CHECK(json_valid(evidence_json)), diagnostics_json TEXT NOT NULL CHECK(json_valid(diagnostics_json)), FOREIGN KEY(pack_id, pack_revision) REFERENCES integration_pack_revisions(pack_id, revision));
CREATE INDEX IF NOT EXISTS integration_checks_target ON integration_checks(pack_id, pack_revision, capability, checked_at);
CREATE TABLE IF NOT EXISTS integration_issues (id TEXT PRIMARY KEY, pack_id TEXT NOT NULL, pack_revision INTEGER NOT NULL, capability TEXT NOT NULL, target_json TEXT NOT NULL CHECK(json_valid(target_json)), reason TEXT NOT NULL, detected_at INTEGER NOT NULL, status TEXT NOT NULL CHECK(status IN ('open','acknowledged','resolved','obsolete')), evidence_json TEXT NOT NULL CHECK(json_valid(evidence_json)), diagnostics_json TEXT NOT NULL CHECK(json_valid(diagnostics_json)), resolved_by_revision INTEGER, FOREIGN KEY(pack_id, pack_revision) REFERENCES integration_pack_revisions(pack_id, revision));
CREATE INDEX IF NOT EXISTS integration_issues_target ON integration_issues(pack_id, pack_revision, capability, status);
`
