// mahas-runtime/inspector/protocol — compatibility re-export for C-* DTOs.
//
// Inspector payload/result contracts are renderer-safe and therefore live in
// mahas-contracts. Runtime handlers continue importing this local seam so the
// implementation can evolve without making clients depend on runtime code.

export type {
  AccessInspectPayload,
  AccessInspectResult,
  AttachedPhase,
  ContextInspectPayload,
  ContextInspectResult,
  ContextUnknown,
  ExecutionGenerationPin,
  GrantInspectSummary,
  GrantScopeSummary,
  HarnessProfileInspectPayload,
  HarnessProfileInspectResult,
  ImplementationOffer,
  ImplementationPreparePayload,
  ImplementationPrepareResult,
  ImplementationPublishPayload,
  ImplementationPublishResult,
  ImplementationRetirePayload,
  ImplementationRetireResult,
  InheritedInput,
  InjectionReceiptPin,
  InterfaceGetPayload,
  InterfaceGetResult,
  LaunchBlocker,
  LaunchPin,
  PlannedComponent,
  RoleImplementationsPayload,
  RoleImplementationsResult,
  RuntimeSnapshotPayload,
  RuntimeSnapshotResult,
  RuntimeSubscribePayload,
  RuntimeSubscribeResult,
  SnapshotEntity,
  StageReceipt,
  StageRecord,
  SurfaceDescribePayload,
  SurfaceDescribeResult,
  SurfaceOperationDescriptor,
  WorkerInspectPayload,
  WorkerInspectResult,
  WorkerInspectTaskAuthority,
  WorkerJoinEvidence,
  WorkerPreparePayload,
  WorkerPrepareResult
} from '../../../mahas-contracts/src/operations/inspector.ts'
