// mahas-runtime — execution-scope CLI connection artifacts (launch/access, IMP-20).
//
// Writes the two files of spec/injection.md §3's exec-root layout that carry
// authority to the worker:
//
//   connection/worker — private credential + endpoint handle, mode 0600,
//                       kept OUT of model input. Body is exactly IMP-12's
//                       WorkerConnectionFile shape (rpc/worker-auth.ts): the
//                       reader enforces the 0600 mode itself.
//   bin/mahas         — scoped CLI launcher: exports MAHAS_CONNECTION_FILE
//                       (IMP-12's env contract) and execs the real mahas
//                       binary. Contains NO secret.
//
// The secret travels: issueBootstrapCredential → this file (0600) → the
// worker CLI's hello frame — never argv, env values, logs, or model input.

import { chmodSync, mkdirSync, renameSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { MAHAS_CONNECTION_FILE_ENV } from '../rpc/index.ts'
import type { WorkerConnectionFile } from '../rpc/index.ts'

/** env var the scoped launcher sets — IMP-12's worker-auth reads this name */
export const WORKER_CONNECTION_ENV = MAHAS_CONNECTION_FILE_ENV

/** exec-root relative locations, spec/injection.md §3 */
export const WORKER_CONNECTION_DIR = 'connection'
export const WORKER_CONNECTION_FILE = 'worker'
export const SCOPED_CLI_DIR = 'bin'
export const SCOPED_CLI_FILE = 'mahas'

/** what launch knows when it writes the handle */
export interface WorkerConnectionInput {
  /** mahasd worker endpoint (mahasdWorkerEndpoint), never the operator path */
  endpoint: string
  credentialId: string
  /** raw bootstrap secret — private to this file (0600), never logged */
  secret: string
  executionId: string
  generation: number
  /** epoch-ms; serialized as an ISO string on disk */
  issuedAt: number
  expiresAt?: number
}

export function workerConnectionPath(execRoot: string): string {
  return join(execRoot, WORKER_CONNECTION_DIR, WORKER_CONNECTION_FILE)
}

export function scopedCliPath(execRoot: string): string {
  return join(execRoot, SCOPED_CLI_DIR, SCOPED_CLI_FILE)
}

function writeAtomic0600(path: string, content: string): void {
  const tmp = `${path}.tmp-${process.pid}`
  writeFileSync(tmp, content, { mode: 0o600 })
  renameSync(tmp, path)
  chmodSync(path, 0o600)
}

/** on-disk body — WorkerConnectionFile plus the launch pin it was issued for */
function connectionBody(input: WorkerConnectionInput): WorkerConnectionFile & {
  execution: { executionId: string; generation: number }
} {
  return {
    version: 1,
    endpoint: input.endpoint,
    credential: { kind: 'worker', credentialId: input.credentialId, secret: input.secret },
    execution: { executionId: input.executionId, generation: input.generation },
    issuedAt: new Date(input.issuedAt).toISOString(),
    ...(input.expiresAt !== undefined ? { expiresAt: new Date(input.expiresAt).toISOString() } : {})
  }
}

/**
 * Persist the worker's private connection handle under
 * <execRoot>/connection/worker — excluded from every model-facing input by
 * the injection layout (spec/injection.md §3: 모델 입력에서 제외).
 */
export function writeWorkerConnection(execRoot: string, input: WorkerConnectionInput): string {
  const dir = join(execRoot, WORKER_CONNECTION_DIR)
  mkdirSync(dir, { recursive: true })
  const path = workerConnectionPath(execRoot)
  writeAtomic0600(path, JSON.stringify(connectionBody(input), null, 2) + '\n')
  return path
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`
}

/**
 * Source of <execRoot>/bin/mahas — a thin shim that points the real CLI at
 * this execution's connection file and forwards argv verbatim. The file is
 * deliberately readable: it carries no secret, only the path.
 */
export function scopedCliLauncherSource(input: {
  connectionPath: string
  /** absolute path of the real mahas binary; defaults to PATH lookup */
  mahasBinary?: string
  executionId?: string
}): string {
  const binaryArgv = input.mahasBinary ? shellQuote(input.mahasBinary) : 'mahas'
  return [
    '#!/bin/sh',
    `# mahas — execution-scoped CLI launcher${input.executionId ? ` (execution ${input.executionId})` : ''}`,
    '# generated by mahasd; do not edit. Carries no credential itself — it only',
    '# points the CLI at the private connection file (mode 0600).',
    `export ${WORKER_CONNECTION_ENV}=${shellQuote(input.connectionPath)}`,
    `exec ${binaryArgv} "$@"`,
    ''
  ].join('\n')
}

/** write bin/mahas under the exec root, mode 0755 */
export function writeScopedCliLauncher(
  execRoot: string,
  input: { connectionPath?: string; mahasBinary?: string; executionId?: string }
): string {
  const dir = join(execRoot, SCOPED_CLI_DIR)
  mkdirSync(dir, { recursive: true })
  const path = scopedCliPath(execRoot)
  const source = scopedCliLauncherSource({
    connectionPath: input.connectionPath ?? workerConnectionPath(execRoot),
    mahasBinary: input.mahasBinary,
    executionId: input.executionId
  })
  writeFileSync(path, source, { mode: 0o755 })
  chmodSync(path, 0o755)
  return path
}
